### ISSUE TITLE
Issue 4: Add tests for Cflat compiler class

### ISSUE THREAD

**Issue by geniuseva** [maemre/compiler-explorer#4]
We are adding tests for Cflat compiler class.

**Comment by geniuseva** [comment]
We finished adding tests for the Cflat Compiler class. And we are working on adding pre-commit test to Git.

Our current error:
  1)  Basic compiler setup
       Should not crash on instantiation:
       Error: Missing language info for Cflat

**Comment by arbie333** [comment]
We fixed the previous bug regarding to basic compiler setup. Also, we passed Cflat testing as shown below.

```
  Basic compiler setup
    ✔ Should not crash on instantiation

  cflatp parsing
    ✔ Parses simple class with one method
```
